################################################################################
# General
################################################################################

# Top Ranking Group By Request
ranking_count = 20

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Show HTTP Response Bytes columns
show_bytes = true

# Percentiles
percentiles = [ 50.0, 90.0, 95.0, 99.0 ]

################################################################################
# Scale
################################################################################

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# for H2O(%{duration}x)
#scale = 0
#effective_digit = 6

# for Envoy
#scale = -3
#effective_digit = 3

# for Rack(Rack::CommonLogger)
#scale = 0
#effective_digit = 4

################################################################################
# Parse
################################################################################

#
# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# H2O example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" %{duration}x"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
#
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+)$'
request_index = 5
status_index = 6
bytes_index = 7
duration_index = 10

#
# Envoy example: use default format
#
#log_format = '^\[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) ([^ ]+) (\d+|-) (\d+|-) (\d+) (\d+) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)"'
#request_index = 2
#status_index = 3
#bytes_index = 6
#duration_index = 7

#
# Rack example: use Rack::CommonLogger, Logger.new("/tmp/app.log")
#
#log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) ([0-9.]+)$'
#request_index = 5
#status_index = 6
#bytes_index = 7
#duration_index = 8

################################################################################
# Bundle
################################################################################

#
# You can aggregate requests by regular expression
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
#[[bundle]]
#regexp = '^(GET|HEAD) /users/[0-9]+\b'
#name = 'GET /memo/*'
#
#[[bundle]]
#regexp = '^(GET|HEAD) /stylesheets/'
#name = 'GET /stylesheets/*'
#
#[[bundle]]
#regexp = '^(GET|HEAD) /images/'
#name = 'GET /images/*'

################################################################################
# Replace
################################################################################

#
# You can replace the part of urls which matched to your regular expressions.
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
#[[replace]]
#regexp = '/[0-9]+(/|\s)'
#replace = '/<num>$1'
#
#[[replace]]
#regexp = '=[0-9]+(&|\s)'
#replace = '=<num>$1'
#
#[[replace]]
#regexp = '\s+HTTP/[0-9.]+$'
#replace = ''

[[replace]]
regexp = '/user/[0-9]+/gacha/index'
replace = '/user/:userID/gacha/index'

[[replace]]
regexp = '/user/[0-9]+/gacha/draw/[0-9]+/[0-9]+'
replace = '/user/:userID/gacha/draw/:gachaID/:n'

[[replace]]
regexp = '/user/[0-9]+/present/index/[0-9]+'
replace = '/user/:userID/present/index/:n'

[[replace]]
regexp = '/user/[0-9]+/present/receive'
replace = '/user/:userID/present/receive'

[[replace]]
regexp = '/user/[0-9]+/item'
replace = '/user/:userID/item'

[[replace]]
regexp = '/user/[0-9]+/card/addexp/[0-9]+'
replace = '/user/:userID/card/addexp/:cardID'

[[replace]]
regexp = '/user/[0-9]+/card'
replace = '/user/:userID/card'

[[replace]]
regexp = '/user/[0-9]+/reward'
replace = '/user/:userID/reward'

[[replace]]
regexp = '/user/[0-9]+/home'
replace = '/user/:userID/home'

[[replace]]
regexp = '/admin/user/[0-9]+/ban'
replace = '/admin/user/:userID/ban'

[[replace]]
regexp = '/admin/user/[0-9]+'
replace = '/admin/user/:userID'

################################################################################
